name: CI

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: GOTO 'Example'
      run: cd Example
    - name: Pod update
      run: |
        cd Example
        pod update
    - name: Run tests
      run: xcodebuild -workspace "HSRange.xcworkspace" -scheme "HSRange-Example" -destination 'platform=iOS Simulator,name=iPhone 8' test
